import Link from "next/link";
import type { Route } from "next";
import { WorkspaceShell } from "@/components/workspace-shell";

export default function ResearchCenterPage() {
  return <WorkspaceShell active="research" breadcrumbs={<><span>Studio Meridian</span><span>/</span><strong>Research</strong></>}>
    <section className="hero directory-hero"><div><div className="eyebrow">Evidence operations</div><h1>Research</h1><p>Monitor evidence, research quality, and unresolved rights questions across your productions.</p></div><div className="hero-actions"><span className="live-data-label"><span className="env-dot" />Parallel-backed research</span></div></section>
    <section className="research-center-grid"><div className="panel research-center-intro"><span className="eyebrow">Research lab</span><h2>Start from a project asset.</h2><p>ClearCut decomposes a rights question into focused research angles—official ownership, licensing, territory restrictions, contact channels, and conflict checks.</p><div className="research-center-steps"><div><strong>01</strong><span>Choose an asset</span></div><div><strong>02</strong><span>Run multi-angle research</span></div><div><strong>03</strong><span>Review evidence and gaps</span></div></div></div><div className="panel research-center-status"><div className="panel-header"><div><h2>Live provider path</h2><p className="panel-subtitle">Configured workspace capabilities</p></div><span className="status-chip active">Live</span></div><div className="provider-row"><span className="provider-icon">P</span><div><strong>Parallel</strong><small>Search, extraction, source provenance, and follow-up research</small></div><span className="provider-state">Connected</span></div><div className="provider-row"><span className="provider-icon provider-icon-blue">V</span><div><strong>Vertex AI</strong><small>Rights signal extraction and explainable clearance cards</small></div><span className="provider-state">Connected</span></div></div></section>
    <section><div className="section-heading"><div><h2>Choose a project</h2><p className="panel-subtitle">Open a project research workspace to inspect live sessions and evidence gaps.</p></div></div><div className="research-project-grid"><Link className="panel research-project-card" href="/projects" as={"/projects" as Route}><span className="eyebrow">Projects</span><h3>Open the project directory</h3><p>Search productions and open the Research tab for asset-level sessions, sources, and follow-ups.</p><span className="directory-open">Browse projects →</span></Link></div></section>
  </WorkspaceShell>;
}
